### ISSUE TITLE
APR prod stage problem 

### ISSUE THREAD

**Issue by mauramalinka** [GilsonLabUCSD/APR#3]
After finishing eq with no problem after "Fixed the manual_removal referenced before assignment bug", now I have problem in a prod stage. In the first window simulation start and mdinfo.01, mdout.01, traj.01 is produced. However the "SEM of the forces" is not checked. No info about it. And then all mdout.02, mdout.03, ..., mdout.20 are produced, of course almost empty. Also rst.01 is empty. Is it an Amber problem or in the APR.py script. Any help will be appreciated.

Thanks,
Maura 

[mdout.01.txt](https://github.com/GilsonLabUCSD/APR/files/1514807/mdout.01.txt)
[mdout.02.txt](https://github.com/GilsonLabUCSD/APR/files/1514808/mdout.02.txt)
[mdout.03.txt](https://github.com/GilsonLabUCSD/APR/files/1514809/mdout.03.txt)

[rst.00.txt](https://github.com/GilsonLabUCSD/APR/files/1514810/rst.00.txt)

**Comment by slochower** [comment]
Hi Maura, 

Can you send the exact command you are using to run the scripts and attach the contents of `restraints.in` and `restraints.dat` in the first window? It looks like the production simulation is running, but something may be failing when it tries to analyze the restraints.

**Comment by mauramalinka** [comment]
Sure,
python2 apr.py prod -i apr.in -s continue
[reference.in.txt](https://github.com/GilsonLabUCSD/APR/files/1514877/reference.in.txt)
[reference.dat.txt](https://github.com/GilsonLabUCSD/APR/files/1514878/reference.dat.txt)

**Comment by slochower** [comment]
Okay, those files look pretty good to me. Let me do a little more digging. 

[This](https://github.com/GilsonLabUCSD/APR/blob/2c2a9a9b5eea2f652c58515e0c6078998efd13fe/apr.py#L695) line checks if the file `restraints.dat` exists, and if so, calls the code to provide the error estimate. I have a feeling the function `get_forces` in `err_estimate.py` is not working properly. For debugging purposes, can you add `print('Forces = ' % Forces)` on line 186 of `err_estimate.py`?

**Comment by slochower** [comment]
Hold on a sec -- I just noticed your restraints files are called `reference.in` and `reference.dat` (I actually see them with a `.txt` extension, but I'm not sure that matters right now). However, the code specifically looks for restraint files called `restraints.dat`, hard-coded. Did you change the name to `reference.in` and `reference.dat` at some point? If so, you'll have to go through the code and change `restraints` → `reference`.

**Comment by slochower** [comment]
Actually, I may have confused myself. Give me a few minutes to figure out the file naming thing, because I do see both files on my installation too. But in the meantime, go ahead with adding the `print` statement to make sure the forces are being read properly.

**Comment by mauramalinka** [comment]
Ok. My mistake as well, I was looking for the file.in and file.dat, so found reference files. I don't have restrain.dat only restrain.in, attached. The txt extension I am adding to be able to attached to github. 
[restraints.in.txt](https://github.com/GilsonLabUCSD/APR/files/1514952/restraints.in.txt)

**Comment by slochower** [comment]
It looks like AMBER crashed because `mdout.001` is truncated. I'm not sure why this has happened, but the command to process the restraints (line [665](https://github.com/GilsonLabUCSD/APR/blob/b7462907631986d3f3a2924fb177511e183e25b7/apr.py#L665)) is not run unless word `TIMINGS` is found in the `mdout` file, indicating a successful trajectory. Ideally, we should have just crashed out when `TIMINGS` is not found. So the next step is figuring out why your simulation crashed...

**Comment by slochower** [comment]
If you want to send the `.inpcrd`, `.prmtop`, and `disang.rest` files for the first window, we can take a look and see if there's anything obvious that might be causing the simulation to crash. But it might end up being something subtle.

**Comment by ghost** [comment]
Agreed. I also suggest carefully checking the conformation to see whether the restraints were set up correctly. That's something that can be easily messed up especially when first starting simulating a new system. Thank you for working on this, Dave!

**Comment by mauramalinka** [comment]
Thank you for your help. It looks like there is a problem with Amber on cluster that I am using. They 're working on it.
