### ISSUE TITLE
APR method to estimate binding free energy of ethanol to a kinase surface

### ISSUE THREAD

**Issue by DDGmichigan** [GilsonLabUCSD/APR#5]
Hi,
I wanted to know if you may provide some input files for the APR method used in bromodomain paper
Thanks

**Comment by slochower** [comment]
Hi, I think you'll be able to find what you're looking for in this repository: https://github.com/GHeinzelmann/BAT.py

At this point, this repository is (mostly) outdated; the code should still work and produce correct results, but it is no longer being maintained or updated. For a more up to date version of the APR code, this repository is more active: https://github.com/slochower/pAPRika

**Comment by DDGmichigan** [comment]
@slochower Thanks for the reply, could I mail you some specific questions I have regarding my kinase system?
Regards

**Comment by slochower** [comment]
You can continue this thread or start a new one here https://github.com/slochower/pAPRika. I'll try to help, if I can.

**Comment by GHeinzelmann** [comment]
Hi Dave, thanks for replying and recommending tha BAT.py code. @DDGmichigan, I am happy to set up a system for you to perform FE calculations on your system, you can just message me at the BAT.py page or send me an e-mail at germanohei@gmail.com.
